server:
  port: 9090

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5431/demo_connection
    username: postgres
    password: Mywhiteshirt29@

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
