server:
  port: 9091

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9098/eureka/

  instance:
    prefer-ip-address: true

kafka:
  topic:
    name: activity-topic

instance:
  prefer-ip-address: true