server:
  port: 9091

spring:
  application:
    name: activity-service

  config:
    import: optional:configserver:http://localhost:9097
  cloud:
    config:
      username: admin
      password: admin

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9098/eureka/

  instance:
    prefer-ip-address: true

kafka:
  topic:
    name: activity-topic