server:
  port: 9093

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: activity-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false   # ✅ ADD THIS
        spring.json.value.default.type: com.fitness.aiservice.model.Activity   # ✅ ADD THIS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9098/eureka/

  instance:
    prefer-ip-address: true

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

kafka:
  topic:
    name: activity-topic